// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Runner {
    get ffiValue(): pointer;


    static create(): Runner;

    run(): void;
}